management:
  endpoints:
    web:
      exposure:
        include: *
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance-id: ${spring.application.name}:${random.uuid}

